Vinipedia/Vinipedia/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/v1/', include('api.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('users/', include('users.urls', namespace='users')),
    # path('', include('core.urls', namespace='core')),
    path('', include(('wines.urls', 'wines'), namespace='wines')),
    path('grapes/', include(('grapes.urls', 'grapes'), namespace='grapes')),
    path('producers/', include(('producers.urls', 'producers'), namespace='producers')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Vinipedia/api/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.APIRoot.as_view(), name=views.APIRoot.name),
    path('wines/', views.WineList.as_view(), name=views.WineList.name),
    path('wines/<int:pk>', views.WineDetail.as_view(), name=views.WineDetail.name),
    path('wines/<int:pk>/evaluations', views.evaluations_per_wine, name='wineevaluations-list'),
    path('evaluation/<int:pk>', views.EvaluationDetail.as_view(), name=views.EvaluationDetail.name),
    path('producers/', views.ProducerList.as_view(), name=views.ProducerList.name),
    path('producers/<int:pk>', views.ProducerDetail.as_view(), name=views.ProducerDetail.name),
    path('producers/<int:pk>/pictures', views.producer_images, name='imagesforproducer-list'),
    path('grapes/', views.GrapesList.as_view(), name=views.GrapesList.name),
    path('grapes/<int:pk>', views.GrapeDetail.as_view(), name=views.GrapeDetail.name)
]

Vinipedia/grapes/urls.py
from django.urls import path
from grapes.views import grapes_list, grape_detail

urlpatterns = [

    path('', grapes_list, name='grapes_list'),
    path('<int:pk>', grape_detail, name='grape_detail'),

]

Vinipedia/producers/urls.py
from django.urls import path

from producers.views import producers_list, producer_detail

urlpatterns = [

    path('', producers_list, name='producers_list'),
    path('<int:pk>', producer_detail, name='producer_detail'),

]

Vinipedia/users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from users import views

app_name = 'users'
urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('edit/', views.edit, name='edit'),
]

Vinipedia/wines/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from wines import views

urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('wines/', views.wine_list, name='wine_list'),
    path('wines/<int:pk>', views.wine_detail, name='wine_detail'),
    path('wines/<str:wine_type>', views.wine_list, name='wine_per_type'),
    path('search/', views.wine_search, name='search'),
]

Vinipedia/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
        {%endblock%}
    </title>
    <link href="{% static "base/base.css" %}" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w==" crossorigin="anonymous" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
</head>
<body>
    <div class="navbar">
        <a href="{% url 'wines:homepage' %}">Homepage</a>
        <a href="{% url 'wines:wine_list' %}">Lista de Vinhos</a>
        <a href="{% url 'grapes:grapes_list' %}">Lista de Uvas</a>
        <a href="{% url 'producers:producers_list' %}">Lista de Produtores</a>
        <div class="user-things">
            {% if request.user.is_authenticated %}
                <a href="{% url 'users:logout' %}">Log-out</a>
                <a href="{% url 'users:edit' %}">Editar Conta</a>
            {% else %}
                <a href="{% url 'users:login' %}">Log-in</a>
                <a href="{% url 'users:register' %}">Registro</a>
            {% endif %}
        </div>
    </div>
    <div class="content">
        {% block content %}
        {%endblock%}
    </div>
</body>
</html>

Vinipedia/templates/homepage.html
{% extends 'base.html' %}
{% block title %}Vinipedia: Homepage{% endblock %}

{% block content %}
<div class="homepage">
    <h1>Vinhos destacados:</h1>
    <div class="random-wines">
        {% for rwine in random_wines %}
            <div class="random-wine">
                <img src={{rwine.picture.url}} alt={{rwine.name}} />
                <h4>{{rwine.producer}}</h4>
                <a href={{rwine.get_absolute_url}}><h3>{{rwine.name}} {{rwine.get_type_display}} {{rwine.year}}</h3></a>
            </div>
        {% endfor %}
    </div>
    <h1>Vinhos mais visitados:</h1>
    <div class="most-visited-wines">
        {% for mwine in most_visited_wines %}
            <div class="most-visited-wine">
                <img src={{mwine.picture.url}} alt={{mwine.name}} />
                <h4>{{mwine.producer}}</h4>
                <a href={{mwine.get_absolute_url}}><h3>{{mwine.name}} {{mwine.get_type_display}} {{mwine.year}}</h3></a>
            </div>
        {% endfor %}
    </div>
    <h1>Vinhos visitados recentemente:</h1>
    <div class="recent-wines">
        {% if recent_wines %}
            {% for wine in recent_wines %}
                <div class="recent-wine">
                    <img src={{wine.picture.url}} alt={{wine.name}} />
                    <h4>{{wine.producer}}</h4>
                    <a href={{wine.get_absolute_url}}><h3>{{wine.name}} {{wine.get_type_display}} {{wine.year}}</h3></a>
                </div>
            {% endfor %}
        {% else %}
            <h1>Não tem nenhuns vinhos recentemente visitados, explore o website!</h1>
        {% endif %}
    </div>
</div>
{% endblock %}

Vinipedia/templates/pagination.html
<div class="pagination">
  <span class="step-links">
    {% if page.has_previous %}
      <a href="?page={{ page.previous_page_number }}{% if request.GET.query %}&query={{ request.GET.query }}{% endif %}"><i class="fas fa-arrow-left"></i></a>
    {% endif %}
    <span class="current">
      Página {{ page.number }} de {{ page.paginator.num_pages }}
    </span>
    {% if page.has_next %}
      <a href="?page={{ page.next_page_number }}{% if request.GET.query %}&query={{ request.GET.query }}{% endif %}"><i class="fas fa-arrow-right"></i></a>
    {% endif %}
  </span>
</div>