Vinipedia/Vinipedia/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/v1/', include('api.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('users/', include('users.urls', namespace='users')),
    # path('', include('core.urls', namespace='core')),
    path('', include(('wines.urls', 'wines'), namespace='wines')),
    path('grapes/', include(('grapes.urls', 'grapes'), namespace='grapes')),
    path('producers/', include(('producers.urls', 'producers'), namespace='producers')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Vinipedia/api/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.APIRoot.as_view(), name=views.APIRoot.name),
    path('wines/', views.WineList.as_view(), name=views.WineList.name),
    path('wines/<int:pk>', views.WineDetail.as_view(), name=views.WineDetail.name),
    path('wines/<int:pk>/evaluations', views.evaluations_per_wine, name='wineevaluations-list'),
    path('evaluation/<int:pk>', views.EvaluationDetail.as_view(), name=views.EvaluationDetail.name),
    path('producers/', views.ProducerList.as_view(), name=views.ProducerList.name),
    path('producers/<int:pk>', views.ProducerDetail.as_view(), name=views.ProducerDetail.name),
    path('producers/<int:pk>/pictures', views.producer_images, name='imagesforproducer-list'),
    path('grapes/', views.GrapesList.as_view(), name=views.GrapesList.name),
    path('grapes/<int:pk>', views.GrapeDetail.as_view(), name=views.GrapeDetail.name)
]

Vinipedia/users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from users import views

app_name = 'users'
urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('edit/', views.edit, name='edit'),
]

Vinipedia/users/models.py
from django.contrib.auth.models import User
from django.db import models


def profile_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT /<id>/<filename>
    return 'user/{0}/{1}'.format(instance.user.id, filename)


class Profile(models.Model):
    user = models.OneToOneField(User, primary_key=True, on_delete=models.CASCADE, related_name='profile')
    picture = models.ImageField(upload_to=profile_directory_path, default='default.jpg')

    def __str__(self):
        return self.user.username

Vinipedia/users/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Profile


class LoginForm(forms.Form):
    username = forms.CharField(max_length=30)
    password = forms.CharField(widget=forms.PasswordInput)


class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(label='Palavra-passe',
                               widget=forms.PasswordInput)
    password2 = forms.CharField(label='Repita a palavra-passe',
                                widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'email')

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('Palavra-passes não são iguais.')
        return cd['password2']


class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')


class ProfileEditForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('picture',)

Vinipedia/users/views.py
from django.shortcuts import render
from users.models import Profile
from users.forms import UserRegistrationForm, UserEditForm, ProfileEditForm
from django.contrib.auth.decorators import login_required


# Create your views here.

def register(request):
    if request.method == 'POST':
        user_form = UserRegistrationForm(request.POST)
        if user_form.is_valid():
            new_user = user_form.save(commit=False)
            new_user.set_password(
                user_form.cleaned_data['password'])
            new_user.save()
            Profile.objects.create(user=new_user)
            return render(request,
                          'users/register_done.html',
                          {'new_user': new_user})
    else:
        user_form = UserRegistrationForm()
    return render(request,
                  'users/register.html',
                  {'user_form': user_form})


@login_required
def edit(request):
    if request.method == 'POST':
        user_form = UserEditForm(instance=request.user,
                                 data=request.POST)
        profile_form = ProfileEditForm(
                                    instance=request.user.profile,
                                    data=request.POST,
                                    files=request.FILES)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            # messages.success(request, 'Profile updated successfully')
        else:
            # messages.error(request, 'Error updating your profile')
            pass
    else:
        user_form = UserEditForm(instance=request.user)
        profile_form = ProfileEditForm(instance=request.user.profile)
    return render(request,
                  'users/edit.html',
                  {'user_form': user_form,
                   'profile_form': profile_form})

Vinipedia/templates/users/edit.html
{% extends "base.html" %}

{% block title %}Vinipedia:Conta{% endblock %}

{% block content %}
<div class="user-forms">
  <h1>Edite a sua conta</h1>
  <p>Consegue editar a sua conta a partir de este formulário:</p>
  <form method="post" enctype="multipart/form-data">
    <!--{{ user_form.as_p }}
    {{ profile_form.as_p }}-->
    <p><label for="id_first_name">Primeiro nome:</label> <input type="text" name="first_name" maxlength="150" id="id_first_name"></p>
    <p><label for="id_last_name">Último nome:</label> <input type="text" name="last_name" maxlength="150" id="id_last_name"></p>
    <p><label for="id_email">Endereço de email:</label> <input type="email" name="email" maxlength="254" id="id_email"></p>
    <p>
      <label for="id_picture">Foto:</label> De momento: <a href="/media/default.jpg">default.jpg</a><br>
      Mudar:
      <input type="file" name="picture" accept="image/*" id="id_picture">
    </p>
    {% csrf_token %}
    <p><input type="submit" value="Guardar alterações"></p>
  </form>
</div>
{% endblock %}

Vinipedia/templates/users/register.html
{% extends "base.html" %}

{% block title %}Vinipedia:Registro{% endblock %}

{% block content %}
<div class="user-forms">
  <h1>Crie uma Conta</h1>
  <p>Por favor, crie uma conta seguindo o seguinte formulário:</p>
  <form method="post">
    <!--{{ user_form.as_p }}-->
      <p>
          <label for="id_username">Nome do usuário:</label>
          <input type="text" name="username" maxlength="150" required="" id="id_username">
          <span class="helptext">Necessita ter 150 caracteres ou menor. Letras, números e @/./+/-/_ são os únicos caracteres possíveis.</span>
      </p>
      <p>
          <label for="id_first_name">Primeiro nome:</label>
          <input type="text" name="first_name" maxlength="150" id="id_first_name">
      </p>
      <p>
          <label for="id_email">Endereço de email:</label>
          <input type="email" name="email" maxlength="254" id="id_email">
      </p>
      <p>
          <label for="id_password">Palavra-passe:</label>
          <input type="password" name="password" required="" id="id_password">
      </p>
      <p>
          <label for="id_password2">Repita a palavra-passe:</label>
          <input type="password" name="password2" required="" id="id_password2">
      </p>
    {% csrf_token %}
    <p><input type="submit" value="Criar a minha conta"></p>
  </form>
</div>
{% endblock %}

Vinipedia/templates/users/register_done.html
{% extends "base.html" %}

{% block title %}Vinipedia:Bem-vindo{% endblock %}

{% block content %}
<div class="user-forms">
  <h1>Bem-vindo {{ new_user.first_name }}!</h1>
  <p>A tua conta foi criada com sucesso. Agora consegues <a href="{% url "users:login" %}">log in</a>.</p>
</div>
{% endblock %}