Vinipedia/Vinipedia/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/v1/', include('api.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('users/', include('users.urls', namespace='users')),
    # path('', include('core.urls', namespace='core')),
    path('', include(('wines.urls', 'wines'), namespace='wines')),
    path('grapes/', include(('grapes.urls', 'grapes'), namespace='grapes')),
    path('producers/', include(('producers.urls', 'producers'), namespace='producers')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Vinipedia/api/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.APIRoot.as_view(), name=views.APIRoot.name),
    path('wines/', views.WineList.as_view(), name=views.WineList.name),
    path('wines/<int:pk>', views.WineDetail.as_view(), name=views.WineDetail.name),
    path('wines/<int:pk>/evaluations', views.evaluations_per_wine, name='wineevaluations-list'),
    path('evaluation/<int:pk>', views.EvaluationDetail.as_view(), name=views.EvaluationDetail.name),
    path('producers/', views.ProducerList.as_view(), name=views.ProducerList.name),
    path('producers/<int:pk>', views.ProducerDetail.as_view(), name=views.ProducerDetail.name),
    path('producers/<int:pk>/pictures', views.producer_images, name='imagesforproducer-list'),
    path('grapes/', views.GrapesList.as_view(), name=views.GrapesList.name),
    path('grapes/<int:pk>', views.GrapeDetail.as_view(), name=views.GrapeDetail.name)
]

Vinipedia/wines/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from wines import views

urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('wines/', views.wine_list, name='wine_list'),
    path('wines/<int:pk>', views.wine_detail, name='wine_detail'),
    path('wines/<str:wine_type>', views.wine_list, name='wine_per_type'),
    path('search/', views.wine_search, name='search'),
]

Vinipedia/wines/models.py
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
import datetime

from django.db.models import Avg
from django.urls import reverse
from grapes.models import Grape
from producers.models import Producer


def wine_directory_path(instance, filename):
    return 'wines/{0}/{1}'.format(instance.name, filename)


class Wine(models.Model):
    YEAR_CHOICES = []
    for r in range(1780, (datetime.datetime.now().year + 1)):
        YEAR_CHOICES.append((r, r))

    TYPE_CHOICES = (
        ('tinto', 'Tinto'),
        ('branco', 'Branco'),
        ('verde', 'Verde'),
        ('verde branco', 'Verde Branco'),
        ('verde tinto', 'Verde Tinto'),
        ('do Porto', 'Do Porto'),
        ('rosé', 'Rosé'),
        ('espumante', 'Espumante')
    )

    name = models.CharField(max_length=100)
    description = models.TextField()
    producer = models.ForeignKey(Producer, on_delete=models.CASCADE, related_name='wines')
    type = models.CharField(choices=TYPE_CHOICES, max_length=25)
    year = models.IntegerField(choices=YEAR_CHOICES, default=datetime.datetime.now().year)
    region = models.CharField(max_length=200)
    alcohol_percentage = models.DecimalField(validators=[MinValueValidator(0.0), MaxValueValidator(100.0)],
                                             max_digits=3, decimal_places=1)
    grapes = models.ManyToManyField(Grape, related_name='wines')
    picture = models.ImageField(upload_to=wine_directory_path)
    visits = models.IntegerField(default=0)

    def get_absolute_url(self):
        return reverse('wines:wine_detail',
                       args=[self.pk])

    def score(self):
        evaluations = self.evaluations.all().aggregate(Avg('score'))
        if evaluations['score__avg'] is not None:
            return round(evaluations['score__avg'], 1)
        else:
            return None

    def __str__(self):
        return self.name


class Evaluation(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    wine = models.ForeignKey(Wine, on_delete=models.CASCADE, related_name='evaluations')
    description = models.TextField()
    score = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(5)])
    created = models.DateField(auto_now_add=True)

    def __str__(self):
        return 'Critic by ' + self.user.username + ' for ' + self.wine.name

Vinipedia/wines/forms.py
from django import forms
from wines.models import Evaluation


class SearchForm(forms.Form):
    query = forms.CharField(max_length=30, label='Pesquisa aqui:')


class EvaluationForm(forms.ModelForm):

    class Meta:
        model = Evaluation
        fields = ('description', 'score')

    def clean(self):
        cleaned_data = super().clean()
        score = cleaned_data.get('score')
        if score > 5 or score < 1:
            raise forms.ValidationError('A avaliação precisa de um valor maior do que 1 ou menor do que 5.')
        return cleaned_data

Vinipedia/wines/views.py
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.shortcuts import render, get_object_or_404, redirect
from wines.models import Wine, Evaluation
from .forms import EvaluationForm
import random
from collections import Counter


def wine_search(request):
    if request.method == 'GET':
        query = request.GET.get("query")
        if query.isnumeric():
            results_without_page = Wine.objects.filter(name__contains=query) | Wine.objects.filter(year=query)
        else:
            results_without_page = Wine.objects.filter(name__contains=query)
        paginator = Paginator(results_without_page, 3)
        page = request.GET.get('page')
        try:
            results = paginator.page(page)
        except PageNotAnInteger:
            results = paginator.page(1)
        except EmptyPage:
            results = paginator.page(paginator.num_pages)

        return render(request, 'wines/wines/search.html', {'results': results, 'query': query, 'page':page})


def wine_list(request, wine_type=None):

    if wine_type:
        object_list = Wine.objects.filter(type=wine_type)
    else:
        object_list = Wine.objects.all()
    paginator = Paginator(object_list, 3)
    page = request.GET.get('page')

    try:
        wines = paginator.page(page)
    except PageNotAnInteger:
        wines = paginator.page(1)
    except EmptyPage:
        wines = paginator.page(paginator.num_pages)

    return render(request, "wines/wines/list.html", {'wines': wines, 'page': page, 'wine_type': wine_type})


def wine_detail(request, pk):
    wine = get_object_or_404(Wine, pk=pk)
    evaluations = Evaluation.objects.filter(wine=wine)
    evaluation_form = None
    new_ev = None
    if request.method == 'POST':
        evaluation_form = EvaluationForm(data=request.POST)
        if evaluation_form.is_valid():
            new_ev = evaluation_form.save(commit=False)
            new_ev.wine = wine
            new_ev.user_id = request.user.id
            new_ev.save()
            return redirect(wine)
    elif request.method == 'GET':
        evaluation_form = EvaluationForm()
        wine.visits = wine.visits + 1
        wine.save()
        recent_wines = list(request.session.get('recent_wines', []))
        if wine.id in recent_wines:
            i = recent_wines.index(wine.id)
            recent_wines.pop(i)
        recent_wines.insert(0, wine.id)
        if len(recent_wines) > 5:
            recent_wines.pop()
        request.session['recent_wines'] = recent_wines
    return render(request, 'wines/wines/detail.html',
                  {'wine': wine, 'evaluations': evaluations, 'evaluation_form': evaluation_form, 'new_ev': new_ev})


def homepage(request):
    wines = list(Wine.objects.all())
    if len(wines) > 5:
        random_wines = random.sample(wines, 5)
    else:
        random_wines = wines.copy()
    recent_wines_sess = request.session.get('recent_wines', [])
    recent_wines = []
    """wines_dict = {}"""
    for wine in wines:
        """wines_dict[str(wine.id)] = wine.visits"""
        if len(recent_wines_sess) > 0:
            if wine.id in recent_wines_sess:
                index = recent_wines_sess.index(wine.id)
                recent_wines.insert(index, wine) #a ordenar pelos mais recentemente visitados primeiro
    """most_visited_wines_counter = Counter(wines_dict).most_common(5)
    most_visited_wines = []
    for pkish in most_visited_wines_counter:
        pk = int(pkish[0])
        visited_wine = get_object_or_404(Wine, pk=pk)
        most_visited_wines.append(visited_wine)""" # gosto de complicar coisas :)
    most_visited_wines = Wine.objects.all().order_by('-visits')[:5]
    return render(request, 'homepage.html',
                  {'random_wines': random_wines,
                   'recent_wines': recent_wines,
                   'most_visited_wines': most_visited_wines})

Vinipedia/templates/wines/wines/detail.html
{% extends 'base.html' %}
{% block title %}Vinepedia: {{wine.name}}{% endblock%}

{% block content %}
    <div class="wine-detail">
        <div class="details">
            <img src={{wine.picture.url}} alt={{wine.name}} />
            <h3 id="producer"><a href={{wine.producer.get_absolute_url}} >{{wine.producer}}</a></h3>
            <h2 id="name">{{wine.name}} {{wine.get_type_display}} {{wine.year}}</h2>
            <h4 id="region">Portugal | {{wine.region}}</h4>
            {% if wine.score %}
                <h4>{{wine.score}}/5.0 <i class="far fa-star"></i></h4>
            {% else %}
                <h4>Sem Avaliações</h4>
            {% endif %}
            <p>Teor alcoólico: {{wine.alcohol_percentage}}</p>
            <p>Uvas: {% for grape in wine.grapes.all %} <a href={{grape.get_absolute_url}}>{{grape.get_name_display}}</a> {% endfor %}</p>
            <h4>Descrição:</h4>
            <p>{{wine.description|linebreaks}}</p>
        </div>
        <div class="wine-evaluations">
            <h1>Avaliações:</h1>
            {% for evaluation in evaluations %}
                <h2>Avaliação {{forloop.counter}}, por {{evaluation.user.username}}, no dia {{ evaluation.created|date:"d/m/Y"}}</h2>
                <img id="user-image" src={{evaluation.user.profile.picture.url}} />
                <h4>{{evaluation.score}}/5.0 <i class="far fa-star"></i></h4>
                <p>{{evaluation.description}}</p>
            {% endfor %}
            {% if user.is_authenticated %}
            <div id="evaluation-form">
                <form method="POST">
                    {% csrf_token %}
                    <!--{{ evaluation_form.as_p }}-->
                    {% if evaluation_form.errors %}
                        <h3>Erro na avaliação:</h3>
                        <p>{{evaluation_form.non_field_errors}}</p>
                    {% endif %}
                    <p>
                        <label for="id_description">Descrição:</label>
                        <textarea name="description" cols="40" rows="10" required="" id="id_description"></textarea>
                    </p>
                    <p>
                        <label for="id_score">Avaliação:</label>
                        <input type="number" name="score" required="" id="id_score">
                    </p>
                    <p><input type="submit" value="Adicionar avaliação"></p>
                </form>
            </div>
            {% else %}
            <h1>Precisa de estar autenticado para criar uma avaliação</h1>
        {% endif %}
        </div>
    </div>
{% endblock %}

Vinipedia/templates/wines/wines/list.html
{% extends 'base.html' %}
{% load wines_tags %}
{% block title %} Vinipedia Wines List {% endblock %}

{%block content%}
    <div class="wines">
        <div class="filters">
            {% search_bar %}
            <h3>Tipos de vinho:</h3>
            <div class="type_filter">
                <a href="{% url "wines:wine_per_type" "tinto" %}">Tinto</a>
                <a href="{% url "wines:wine_per_type" "branco" %}">Branco</a>
                <a href="{% url "wines:wine_per_type" "verde" %}">Verde</a>
                <a href="{% url "wines:wine_per_type" "verde branco" %}">Verde Branco</a>
                <a href="{% url "wines:wine_per_type" "verde tinto" %}">Verde Tinto</a>
                <a href="{% url "wines:wine_per_type" "do Porto" %}">Do Porto</a>
                <a href="{% url "wines:wine_per_type" "rosé" %}">Rosé</a>
                <a href="{% url "wines:wine_per_type" "espumante" %}">Espumante</a>
            </div>
        </div>
        {%for wine in wines%}
        <div class="wine">
            <img src={{wine.picture.url}} alt={{wine.name}} />
            <div class="text">
                <h4><a href={{wine.producer.get_absolute_url}}>{{wine.producer}}</a></h4>
                <h2><a href={{wine.get_absolute_url}}>{{wine.name}} {{wine.get_type_display}} {{wine.year}}</a></h2>
                <h3>{{wine.region}}</h3>
                {% if wine.score %}
                    <h4>{{wine.score}}/5.0 <i class="far fa-star"></i></h4>
                {% else %}
                    <h4>Sem Avaliações</h4>
                {% endif %}
            </div>
        </div>
        {%endfor%}
        </div>
    {% include 'pagination.html' with page=wines %}
{% endblock %}

Vinipedia/templates/wines/wines/search.html
{% extends "base.html" %}
{% load wines_tags %}

{% block title %}Vinipedia: Lista de Vinhos{% endblock %}

{% block content %}
<div class="search">
    <h1>Vinhos procurados com: "<em>{{query}}</em>"</h1>
    <div class="filters">
      {% search_bar %}
    </div>
    {% for wine in results %}
        <div class="wine">
            <img src={{wine.picture.url}} alt={{wine.name}} />
            <div class="text">
                <h4>{{wine.producer}}</h4>
                <h2><a href={{wine.get_absolute_url}}>{{wine.name}} {{wine.get_type_display}} {{wine.year}}</a></h2>
                <h3>{{wine.region}}</h3>
            </div>
        </div>
    {%endfor%}
    {% include 'pagination.html' with page=results %}
</div>
{% endblock %}

Vinipedia/templates/wines/wines/search_bar.html
<form action="{% url "wines:search" %}" method="GET">
    {{ search_form.as_p }}
    <input type="submit" value="Pesquisa">
</form>